name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  secure-memory:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
    - name: Checkout the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Cache Go packages
      uses: actions/cache@1a9e2138d905efd099035b49d8b7a3888c653ca8
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Build
      run: |
        cd go/securememory
        ./scripts/build.sh
    - name: Unit tests
      run: |
        cd go/securememory
        ./scripts/test.sh
    - name: Benchmark tests
      run: |
        cd go/securememory
        ./scripts/benchmark_test.sh
    - name: Static analysis
      run: |
        cd go/securememory
        ./scripts/lint.sh
  app-encryption:
    needs: secure-memory
    runs-on: ubuntu-latest
    container:
      image: golang:1.16
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    services:
      dynamodb:
        image: amazon/dynamodb-local
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Password123
    steps:
    - name: Checkout the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Cache Go packages
      uses: actions/cache@1a9e2138d905efd099035b49d8b7a3888c653ca8
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Build
      run: |
        cd go/appencryption
        ./scripts/build.sh
    - name: Unit tests
      run: |
        cd go/appencryption
        ./scripts/test.sh
    - name: Benchmark tests
      run: |
        cd go/appencryption
        ./scripts/benchmark_test.sh
    - name: Static analysis
      run: |
        cd go/appencryption
        ./scripts/lint.sh
  reference-app:
    needs: app-encryption
    runs-on: ubuntu-latest
    container:
      image: golang:1.16
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
    - name: Checkout the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Cache Go packages
      uses: actions/cache@1a9e2138d905efd099035b49d8b7a3888c653ca8
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Build
      run: |
        cd samples/go/referenceapp
        ./scripts/build.sh
    - name: Static analysis
      run: |
        cd samples/go/referenceapp
        ./scripts/lint.sh
