name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  secure-memory:
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/maven-openjdk11
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
    - name: Checkout the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Set up Java
      uses: actions/setup-java@8764a52df183aa0ccea74521dfd9d506ffc7a19a
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Java packages
      uses: actions/cache@1a9e2138d905efd099035b49d8b7a3888c653ca8
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build
      run: |
        cd java/secure-memory
        ./scripts/clean.sh
        ./scripts/build.sh
    - name: Test
      run: |
        cd java/secure-memory
        ./scripts/test.sh
  app-encryption:
    needs: secure-memory
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/maven-openjdk11
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
    - name: Checkout the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Set up Java
      uses: actions/setup-java@8764a52df183aa0ccea74521dfd9d506ffc7a19a
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Java packages
      uses: actions/cache@1a9e2138d905efd099035b49d8b7a3888c653ca8
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build
      run: |
        cd java/app-encryption
        ./scripts/clean.sh
        ./scripts/build.sh
    - name: Test
      run: |
        . ./.github/workflows/set_env_variables.sh
        cd java/app-encryption
        ./scripts/integration_test.sh
